baseURL = 'https://codecommons.net'
languageCode = 'en-us'
title = "Code Commons"
videoembed= "<iframe width="560" height="315" src="https://www.youtube.com/embed/sCNlt5nvSI8?si=cPzaCyr_NmWRAl1x&amp;clip=UgkxUU4dMYoLd4lC2llDuJANLX9TMCoYKTBo&amp;clipt=EAAYmHU" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>"

[permalinks]
blog = "/:filename/"

# See https://feathericons.com/
# The value of pre is the icon name
[menu]
[[menu.main]]
name = "Home"
pre = "home"
url = "/"
weight = 1
[[menu.main]]
name = "About"
pre = "edit"
url = "/about/"
weight = 2

[params]
dateFormat = "Jan 2, 2006"

[taxonomies]
tag = "tags"
